name: minime-mcp-system

services:
  minime-mcp:
    image: manujbawa/minimemcp:latest
    container_name: ${CONTAINER_NAME:-minimemcp}
    restart: always

    ports:
      - "${HOST_UI_PORT:-9000}:9000"
      - "${HOST_MCP_PORT:-8000}:8000"
      - "${HOST_POSTGRES_PORT:-5432}:5432"
      - "${HOST_DEBUG_PORT:-9229}:9229"

    volumes:
      - data:/data
      - wal:/data/postgres_wal
      - docs:/app/data/documents

    env_file:
      - minime.env

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Volumes with dynamic naming using environment variables
# Volume names use ${VOLUME_NAME} from minime.env (default: minime-mcp-v18)
volumes:
  data:
    name: ${VOLUME_NAME:-minime-mcp-v18}-data
  wal:
    name: ${VOLUME_NAME:-minime-mcp-v18}-wal
  docs:
    name: ${VOLUME_NAME:-minime-mcp-v18}-docs
