version: '3.8'

services:
  minime-mcp:
    image: manujbawa/minimemcp:latest
    container_name: ${CONTAINER_NAME:-minimemcp}
    restart: always

    ports:
      - "${UI_PORT:-9000}:9000"
      - "${MCP_PORT:-8000}:8000"
      - "${POSTGRES_PORT:-5432}:5432"
      - "${OLLAMA_PORT:-11434}:11434"
      - "${DEBUG_PORT:-9229}:9229"

    volumes:
      - ${VOLUME_NAME:-minime-mcp-data}:/data

    env_file:
      - minime.env

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${MCP_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  minime-mcp-data:
    external: false
